---
# tasks file for db-tier
- name: install {{ db_tier_packages }}
  yum:
    name: "{{ db_tier_packages }}"
    state: latest

- name: Enable Postgres at boot
  service:
    name: postgresql
    enabled: yes

- name: Check if PostgreSQL database is initialized.
  stat:
    path: "/var/lib/pgsql/data/PG_VERSION"
  register: pgdata_dir_version

- name: initilize postgres
  command: postgresql-setup initdb
  when: not pgdata_dir_version.stat.exists

- name: initilize postgres some more
  command: chkconfig postgresql on
- name: start postgres
  service:
    name: postgresql.service
    state: started